services:
  tw-stock-app:
    image: popojk/tw-stock-app:latest
    container_name: tw-stock-app
    ports:
      - 8080:8080
    external_links:
      - tw-stock-db:tw-stock-db
      - tw-stock-redis:tw-stock-redis
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
        limits:
          cpus: '1'
          memory: 0.8G

  tw-stock-frontend:
    image: popojk/tw-stock-frontend:latest
    restart: unless-stopped
    container_name: tw-stock-frontend
    domainname: twstock
    ports:
      - 80:80
      - 443:443
    external_links:
      - tw-stock-app
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
        limits:
          cpus: '1'
          memory: 0.8G

  tw-stock-db:
    image: popojk/tw-stock-db:latest
    container_name: tw-stock-db
    environment:
      MYSQL_DATABASE: tw_stock-db
      MYSQL_USER: root
      MYSQL_PASSWORD: Ss6450065
    ports:
      - 3306:3306
    networks:
      - twstock-network
    external_links:
      - tw-stock-app:tw-stock-app
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
        limits:
          cpus: '0.5'
          memory: 0.5G

  tw-stock-redis:
    image: popojk/tw-stock-redis:latest
    container_name: tw-stock-redis
    ports:
      - 6379:6379
    networks:
      - twstock-network
    external_links:
      - tw-stock-app:tw-stock-app
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 0.5G
        limits:
          cpus: '0.5'
          memory: 0.5G

networks:
  twstock-network:
    driver: bridge
